baseURL = "https://institutionengineering.com"
languageCode = "en-us"
title = "Institution Engineering"
theme = "PaperMod"

[params]
  env = "production"
  ShowSearch = true
  ShowPostList = true
  ShowPostNavLinks = true

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Search"
  url = "/search/"
  weight = 2

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[outputs]
  home = ["HTML", "RSS", "JSON"]
